import type { Developer, Project } from "./types";

export const mockDevelopers: Developer[] = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    headline: "I Fix What AI Breaks | 50+ Rescues | Ex-Google",
    bio: "Former Google engineer. I charge 'a fuckload' but I'll turn your 60k lines of AI slop into 8k lines that actually work. Fixed that infamous Reddit timesheet disaster. Your cognitive load ends here.",
    location: "San Francisco, CA",
    timezone: "PST",
    yearsExperience: 10,
    specialties: [
      "Code Refactoring",
      "Architecture Design",
      "Performance Optimization",
      "AI Cleanup",
    ],
    technologies: ["Python", "TypeScript", "JavaScript", "Go", "Rust"],
    frameworks: ["FastAPI", "React", "Next.js", "Django", "Node.js"],
    hourlyRate: 150,
    projectMinimum: 5000,
    preferredProjectSize: "large",
    portfolioUrl: "https://sarahchen.dev",
    githubUrl: "https://github.com/sarahchen",
    linkedinUrl: "https://linkedin.com/in/sarahchen",
    projectsCompleted: 52,
    avgRating: 4.9,
    totalReviews: 48,
    isAvailable: true,
    responseTime: "< 4 hours",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2025-07-20"),
    featured: true,
    verified: true,
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    email: "marcus@example.com",
    headline: "Timesheet Disaster Fixer | AI Pattern Recognition Expert",
    bio: "Remember that Reddit post about 'insidiously good looking' AI code? I fixed it. I know every pattern AI uses to hide bugs. Your beautifully formatted disaster is safe with me.",
    location: "Austin, TX",
    timezone: "CST",
    yearsExperience: 8,
    specialties: [
      "Python Development",
      "API Design",
      "Testing",
      "Documentation",
    ],
    technologies: ["Python", "JavaScript", "SQL", "Redis"],
    frameworks: ["FastAPI", "Flask", "Django", "Vue.js"],
    hourlyRate: 120,
    projectMinimum: 3000,
    preferredProjectSize: "medium",
    portfolioUrl: "https://marcusdev.io",
    githubUrl: "https://github.com/mrodriguez",
    projectsCompleted: 34,
    avgRating: 4.8,
    totalReviews: 31,
    isAvailable: true,
    responseTime: "< 24 hours",
    createdAt: new Date("2023-03-20"),
    updatedAt: new Date("2025-07-18"),
    featured: true,
    verified: true,
  },
  {
    id: "3",
    name: "Elena Volkov",
    email: "elena@example.com",
    headline: "React Render Loop Terminator | useState Untangler",
    bio: "Former Meta engineer. When your React has 15 conflicting useState hooks and infinite render loops, I'm your person. I've seen every useEffect disaster AI can create.",
    location: "New York, NY",
    timezone: "EST",
    yearsExperience: 7,
    specialties: [
      "Frontend Development",
      "React Optimization",
      "Component Architecture",
      "Performance",
    ],
    technologies: ["TypeScript", "JavaScript", "CSS", "HTML"],
    frameworks: ["React", "Next.js", "Vue.js", "Svelte", "Tailwind CSS"],
    hourlyRate: 140,
    projectMinimum: 4000,
    preferredProjectSize: "any",
    githubUrl: "https://github.com/evolkov",
    linkedinUrl: "https://linkedin.com/in/elenavolkov",
    projectsCompleted: 28,
    avgRating: 5.0,
    totalReviews: 26,
    isAvailable: true,
    responseTime: "< 1 hour",
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2025-07-19"),
    verified: true,
  },
  {
    id: "4",
    name: "James Park",
    email: "james@example.com",
    headline: "Cognitive Load Reducer | 80% Correct Code Fixer",
    bio: "'Code is written once but read thousands of times' - and AI doesn't give a shit. I fix the cognitive load nightmare of 80% correct code. Your unused props and phantom functions end here.",
    location: "Seattle, WA",
    timezone: "PST",
    yearsExperience: 6,
    specialties: [
      "MVP Development",
      "Rapid Prototyping",
      "Full Stack",
      "Deployment",
    ],
    technologies: ["JavaScript", "Python", "TypeScript", "SQL"],
    frameworks: ["Node.js", "Express", "React", "PostgreSQL", "MongoDB"],
    hourlyRate: 100,
    projectMinimum: 2000,
    preferredProjectSize: "small",
    portfolioUrl: "https://jamespark.dev",
    projectsCompleted: 42,
    avgRating: 4.7,
    totalReviews: 38,
    isAvailable: true,
    responseTime: "< 4 hours",
    createdAt: new Date("2023-04-05"),
    updatedAt: new Date("2025-07-21"),
    verified: true,
  },
  {
    id: "5",
    name: "Priya Sharma",
    email: "priya@example.com",
    headline: "Factory Factory Destroyer | Over-Architecture Specialist",
    bio: "Ex-Amazon. When AI creates factories to make factories to render a button, call me. I've untangled every over-architected nightmare LLMs produce. 'AI code ranges from perfect to absolutely retarded' - I fix the latter.",
    location: "Toronto, Canada",
    timezone: "EST",
    yearsExperience: 12,
    specialties: [
      "Backend Architecture",
      "Microservices",
      "Database Design",
      "Scalability",
    ],
    technologies: ["Java", "Python", "Go", "Kubernetes", "AWS"],
    frameworks: ["Spring Boot", "FastAPI", "Gin", "gRPC"],
    hourlyRate: 180,
    projectMinimum: 8000,
    preferredProjectSize: "large",
    githubUrl: "https://github.com/psharma",
    linkedinUrl: "https://linkedin.com/in/priyasharma",
    projectsCompleted: 38,
    avgRating: 4.9,
    totalReviews: 35,
    isAvailable: false,
    responseTime: "2-3 days",
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2025-07-15"),
    verified: true,
  },
  {
    id: "6",
    name: "Alex Thompson",
    email: "alex@example.com",
    headline: "Vibe Code Debugger | Won't Judge Your AI Mess | Affordable",
    bio: "Recent grad who uses AI daily - so I know exactly where it fails. I won't judge your vibe-coded disaster. Affordable rates because I remember being stuck in debugging hell too.",
    location: "Denver, CO",
    timezone: "MST",
    yearsExperience: 2,
    specialties: ["Code Cleanup", "Bug Fixing", "Documentation", "Testing"],
    technologies: ["JavaScript", "Python", "HTML", "CSS"],
    frameworks: ["React", "Express", "Flask"],
    hourlyRate: 60,
    projectMinimum: 500,
    preferredProjectSize: "small",
    githubUrl: "https://github.com/alexthompson",
    projectsCompleted: 12,
    avgRating: 4.5,
    totalReviews: 10,
    isAvailable: true,
    responseTime: "< 1 hour",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-07-20"),
    verified: false,
  },
];

export const sampleProjects: Project[] = [
  {
    id: "1",
    title: "The Infamous Timesheet Disaster",
    description:
      "AI-generated timesheet software that was causing staff arguments. The code looked perfect but completely misunderstood the business logic.",
    beforeLines: 60000,
    afterLines: 8000,
    duration: "14 days",
    technologies: ["Python", "FastAPI", "PostgreSQL", "Redis"],
    testimonial:
      "They admitted they just gave ChatGPT examples and used the code. I charged them a fuckload to fix it.",
    clientName: "Anonymous",
    clientCompany: "r/devops",
  },
  {
    id: "2",
    title: "React Component with 15 useState Hooks",
    description:
      "Component had inconsistent states, unused props, and a weird loop causing render issues. Classic AI overengineering.",
    beforeLines: 45000,
    afterLines: 12000,
    duration: "7 days",
    technologies: ["React", "TypeScript", "Next.js"],
    testimonial:
      "Took longer to fix than it would've taken to write from scratch. The cognitive load was brutal.",
    clientName: "DevOps Engineer",
    clientCompany: "Tech Startup",
  },
  {
    id: "3",
    title: "API That Called Non-Existent Endpoints",
    description:
      "AI hallucinated an entire API structure. Beautiful code calling phantom functions and endpoints that never existed.",
    beforeLines: 30000,
    afterLines: 5000,
    duration: "10 days",
    technologies: ["Node.js", "Express", "MongoDB"],
    testimonial:
      "The AI created helper functions referencing libraries we never installed. Insidiously good looking but completely broken.",
    clientName: "CTO",
    clientCompany: "SaaS Startup",
  },
  {
    id: "4",
    title: "Simple CRUD with 47 Abstraction Layers",
    description:
      "What should have been 500 lines became 20k lines. Factories creating factories to render a button. Peak AI overarchitecture.",
    beforeLines: 20000,
    afterLines: 800,
    duration: "5 days",
    technologies: ["Java", "Spring Boot", "PostgreSQL"],
    testimonial:
      "AI code ranges from perfect to absolutely retarded. This was the latter. Complete rewrite was faster than debugging.",
    clientName: "Lead Developer",
    clientCompany: "Enterprise Corp",
  },
];
