import type { Developer, Project } from "./types";

export const mockDevelopers: Developer[] = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    headline: "Senior Full Stack Developer | AI Code Rescue Specialist",
    bio: "Former Google engineer with 10+ years experience. Rescued 50+ founders from AI debugging hell. I specialize in turning 60k-line nightmares into clean, maintainable codebases.",
    location: "San Francisco, CA",
    timezone: "PST",
    yearsExperience: 10,
    specialties: [
      "Code Refactoring",
      "Architecture Design",
      "Performance Optimization",
      "AI Cleanup",
    ],
    technologies: ["Python", "TypeScript", "JavaScript", "Go", "Rust"],
    frameworks: ["FastAPI", "React", "Next.js", "Django", "Node.js"],
    hourlyRate: 150,
    projectMinimum: 5000,
    preferredProjectSize: "large",
    portfolioUrl: "https://sarahchen.dev",
    githubUrl: "https://github.com/sarahchen",
    linkedinUrl: "https://linkedin.com/in/sarahchen",
    projectsCompleted: 52,
    avgRating: 4.9,
    totalReviews: 48,
    isAvailable: true,
    responseTime: "< 4 hours",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2025-07-20"),
    featured: true,
    verified: true,
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    email: "marcus@example.com",
    headline: "Python Expert | FastAPI Specialist | Clean Code Advocate",
    bio: "I turn AI spaghetti into clean, tested, documented code. Specialized in Python/FastAPI projects. Fixed that infamous 60k line Reddit project!",
    location: "Austin, TX",
    timezone: "CST",
    yearsExperience: 8,
    specialties: [
      "Python Development",
      "API Design",
      "Testing",
      "Documentation",
    ],
    technologies: ["Python", "JavaScript", "SQL", "Redis"],
    frameworks: ["FastAPI", "Flask", "Django", "Vue.js"],
    hourlyRate: 120,
    projectMinimum: 3000,
    preferredProjectSize: "medium",
    portfolioUrl: "https://marcusdev.io",
    githubUrl: "https://github.com/mrodriguez",
    projectsCompleted: 34,
    avgRating: 4.8,
    totalReviews: 31,
    isAvailable: true,
    responseTime: "< 24 hours",
    createdAt: new Date("2023-03-20"),
    updatedAt: new Date("2025-07-18"),
    featured: true,
    verified: true,
  },
  {
    id: "3",
    name: "Elena Volkov",
    email: "elena@example.com",
    headline: "Frontend Specialist | React/Next.js Expert | UI/UX Focus",
    bio: "Former Meta engineer. I fix broken React apps and turn messy component hierarchies into clean, performant applications. Specialist in fixing AI-generated frontend code.",
    location: "New York, NY",
    timezone: "EST",
    yearsExperience: 7,
    specialties: [
      "Frontend Development",
      "React Optimization",
      "Component Architecture",
      "Performance",
    ],
    technologies: ["TypeScript", "JavaScript", "CSS", "HTML"],
    frameworks: ["React", "Next.js", "Vue.js", "Svelte", "Tailwind CSS"],
    hourlyRate: 140,
    projectMinimum: 4000,
    preferredProjectSize: "any",
    githubUrl: "https://github.com/evolkov",
    linkedinUrl: "https://linkedin.com/in/elenavolkov",
    projectsCompleted: 28,
    avgRating: 5.0,
    totalReviews: 26,
    isAvailable: true,
    responseTime: "< 1 hour",
    createdAt: new Date("2023-02-10"),
    updatedAt: new Date("2025-07-19"),
    verified: true,
  },
  {
    id: "4",
    name: "James Park",
    email: "james@example.com",
    headline: "Full Stack Developer | Startup Specialist | Quick Turnaround",
    bio: "I help non-technical founders escape AI code disasters. Rebuilt 20+ AI-generated MVPs into production-ready applications. Fast, transparent, fixed pricing.",
    location: "Seattle, WA",
    timezone: "PST",
    yearsExperience: 6,
    specialties: [
      "MVP Development",
      "Rapid Prototyping",
      "Full Stack",
      "Deployment",
    ],
    technologies: ["JavaScript", "Python", "TypeScript", "SQL"],
    frameworks: ["Node.js", "Express", "React", "PostgreSQL", "MongoDB"],
    hourlyRate: 100,
    projectMinimum: 2000,
    preferredProjectSize: "small",
    portfolioUrl: "https://jamespark.dev",
    projectsCompleted: 42,
    avgRating: 4.7,
    totalReviews: 38,
    isAvailable: true,
    responseTime: "< 4 hours",
    createdAt: new Date("2023-04-05"),
    updatedAt: new Date("2025-07-21"),
    verified: true,
  },
  {
    id: "5",
    name: "Priya Sharma",
    email: "priya@example.com",
    headline: "Backend Architect | Microservices Expert | Scale Specialist",
    bio: "Ex-Amazon engineer. I fix architectural disasters and turn monolithic messes into scalable systems. Specialist in fixing AI-generated backend architectures.",
    location: "Toronto, Canada",
    timezone: "EST",
    yearsExperience: 12,
    specialties: [
      "Backend Architecture",
      "Microservices",
      "Database Design",
      "Scalability",
    ],
    technologies: ["Java", "Python", "Go", "Kubernetes", "AWS"],
    frameworks: ["Spring Boot", "FastAPI", "Gin", "gRPC"],
    hourlyRate: 180,
    projectMinimum: 8000,
    preferredProjectSize: "large",
    githubUrl: "https://github.com/psharma",
    linkedinUrl: "https://linkedin.com/in/priyasharma",
    projectsCompleted: 38,
    avgRating: 4.9,
    totalReviews: 35,
    isAvailable: false,
    responseTime: "2-3 days",
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2025-07-15"),
    verified: true,
  },
  {
    id: "6",
    name: "Alex Thompson",
    email: "alex@example.com",
    headline: "Junior Developer | AI Cleanup Enthusiast | Budget-Friendly",
    bio: "Recent bootcamp grad specializing in fixing AI-generated code. I offer affordable rates and work closely with senior mentors. Great for smaller projects!",
    location: "Denver, CO",
    timezone: "MST",
    yearsExperience: 2,
    specialties: ["Code Cleanup", "Bug Fixing", "Documentation", "Testing"],
    technologies: ["JavaScript", "Python", "HTML", "CSS"],
    frameworks: ["React", "Express", "Flask"],
    hourlyRate: 60,
    projectMinimum: 500,
    preferredProjectSize: "small",
    githubUrl: "https://github.com/alexthompson",
    projectsCompleted: 12,
    avgRating: 4.5,
    totalReviews: 10,
    isAvailable: true,
    responseTime: "< 1 hour",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-07-20"),
    verified: false,
  },
];

export const sampleProjects: Project[] = [
  {
    id: "1",
    title: "Business Intelligence Dashboard Cleanup",
    description:
      "Transformed 60k lines of AI-generated Python/FastAPI code into 8k lines of clean, maintainable code",
    beforeLines: 60000,
    afterLines: 8000,
    duration: "14 days",
    technologies: ["Python", "FastAPI", "PostgreSQL", "Redis"],
    testimonial:
      "What started as a debugging nightmare became a production-ready app. Worth every penny!",
    clientName: "John D.",
    clientCompany: "DataFlow Inc",
  },
  {
    id: "2",
    title: "E-commerce Platform Rescue",
    description:
      "Rebuilt messy React/Node.js app with proper component architecture and state management",
    beforeLines: 45000,
    afterLines: 12000,
    duration: "21 days",
    technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    testimonial:
      "They turned our AI mess into something our team can actually maintain and extend.",
    clientName: "Sarah M.",
    clientCompany: "ShopEasy",
  },
];
