name = "cleanmyaislop"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

# Environment variables (non-sensitive)
[vars]
NODE_ENV = "production"
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAABnFtp8SldxpzLtv"

# Secrets should be added via CLI:
# wrangler pages secret put DATABASE_URL
# wrangler pages secret put AUTH_SECRET
# wrangler pages secret put TURNSTILE_SECRET_KEY

# Note: Build command should be run separately:
# npm run build
# wrangler pages deploy .svelte-kit/cloudflare